# Generated by Django 5.2.3 on 2025-06-30 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_program_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilities',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='facilities',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='maximum capacity of the facility', null=True),
        ),
        migrations.AddField(
            model_name='facilities',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of of the facility ', null=True, upload_to='facilities/'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this facility currently available'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilities',
            name='author',
            field=models.CharField(help_text='Name of the facility e.g Modern Computer Lab', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='description',
            field=models.TextField(help_text='Detailed description of the Facility'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='location',
            field=models.CharField(help_text='Physical location of the facility', max_length=200),
        ),
    ]
