# Generated by Django 5.2.3 on 2025-07-01 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_facilities_options_facilities_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-is_featured', '-date_added'], 'verbose_name': 'School Resource/Facility', 'verbose_name_plural': 'School Resources/Facilities'},
        ),
        migrations.AddField(
            model_name='resource',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_resources', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum capacity if applicable', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='resource',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Person in charge', max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display prominently on facilities page'),
        ),
        migrations.AddField(
            model_name='resource',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='e.g., 8:00 AM - 6:00 PM', max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements or rules'),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('laboratory', 'Laboratory'), ('library', 'Library'), ('classroom', 'Classroom'), ('technology', 'Technology'), ('maker_space', 'Maker Space'), ('computer_lab', 'Computer Lab'), ('research_center', 'Research Center'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
