# Generated by Django 5.2.3 on 2025-07-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_resource_options_resource_added_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='date_applied',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='application',
            name='attestation',
            field=models.FileField(default=1, upload_to='attestation/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
