# Generated by Django 5.2.3 on 2025-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_socialmedialink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='program',
        ),
        migrations.AddField(
            model_name='contact',
            name='office_hours',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('feedback', 'Feedback & Suggestions'), ('partnership', 'Partnership Opportunities'), ('complaint', 'Complaint'), ('billing', 'Billing & Payment'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('media', 'Media & Press'), ('careers', 'Career Opportunities'), ('other', 'Other (Please specify)')], default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_link',
        ),
        migrations.AddField(
            model_name='contact',
            name='social_link',
            field=models.ManyToManyField(blank=True, to='website.socialmedialink'),
        ),
    ]
