# Generated by Django 5.2.3 on 2025-07-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
