# Generated by Django 5.2.3 on 2025-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_teammember_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextadmission',
            old_name='end_date',
            new_name='next_admission',
        ),
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
